apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-api
  namespace: app
  labels:
    app: document-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: document-api
  template:
    metadata:
      labels:
        app: document-api
    spec:
      serviceAccountName: document-api-sa
      containers:
        - name: api
          image: <your-registry>/document-api:latest
          ports:
            - containerPort: 80
          env:
            - name: S3_BUCKET
              value: <your-s3-bucket>
            - name: DYNAMODB_TABLE
              value: <your-dynamodb-table>
            - name: AWS_REGION
              value: <aws-region>
            - name: SQS_QUEUE_URL
              value: <your-sqs-queue-url>
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
