apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: document-api-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: document-api
  namespaceSelector:
    matchNames:
      - app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
